config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    collection  do
      get :user
    end
  end
  #SESSION
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  #USER
  get 'sign_up', to: 'users#new'
  resources :users, except: [:new]

  #TASK
  # root 'tasks#index'

  #get 'tags/:tag', to: "tasks#index", as: :tags

  #PAGE
  root 'pages#index'

  #ADMIN
  namespace :admin, path: 'admin' do
    resources :users
    get 'sign_up', to: 'users#new'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

end

app/views/shared/frontend/_flash.html.erb
<div class="alert alert-secondary" role="alert">
  <%= notice %>
</div>

app/views/shared/frontend/_footer.html.erb
<footer class="py-4 bg-dark text-white">
  <div class="px-5 text-right">
    <span>Copyright &copy; 2019 TaskManager INc.</span>
  </div>
</footer>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Task Manager", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to t('.my_task'), user_tasks_path(current_user) , class: 'nav-link' %>
      </li>
      <% if logged_in? && current_user.admin? %>
      <li class="nav-item">
        <%= link_to t('tasks.index_task'), tasks_path , class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('tasks.index_user'), admin_users_path , class: 'nav-link' %>
      </li>
      <% end %>
    </ul>

    <%= form_tag(tasks_path, :method => "get", :class => 'd-flex', :id => 'search_bar') do %>
      <form class="form-inline my-2 my-lg-10">
        <% if ransack_obj %>
          <%= search_form_for ransack_obj do |f| %>
            <div><%= f.input :tags_name_eq, ad: :select, label: false, collection: Tag.all, label_method: :name, value_method: :name, :required => false %></div>
            <div><%= f.search_field :title_or_content_cont, class:"form-control mr-sm-2", type:"search", placeholder:"搜尋標題或內容"%></div>
            <div><%= f.submit class:"btn btn-outline-light my-2 my-sm-0" %></div>
          <% end %>
        <% end %>
      </form>
    <% end %>
  
    <ul class="navbar-nav">
        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username.upcase %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to t('.my_task'), user_tasks_path(current_user) , class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>          
            <%= link_to t('.new_task'), new_task_path , class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to t('.settings'), edit_user_path(current_user) , class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to t('.logout'), logout_path, method:'delete' , class: 'dropdown-item'%>
          </div>
        </li> 
        <% else %>
          <li class="nav-item">
            <%= link_to "登入", login_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "註冊", sign_up_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t('.language') %>
          </a>
          <div class="dropdown-menu p-2" aria-labelledby="navbarDropdown">
            <%= link_to('中文', :locale => 'zh-TW', class: 'dropdown-item') %>
            <div class="dropdown-divider"></div> 
            <%= link_to('English', :locale => 'en', class: 'dropdown-item') %>
          </div>
        </li>       
        
    </ul>
  </div>
</nav>