config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    collection  do
      get :user
    end
  end
  #SESSION
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  #USER
  get 'sign_up', to: 'users#new'
  resources :users, except: [:new]

  #TASK
  # root 'tasks#index'

  #get 'tags/:tag', to: "tasks#index", as: :tags

  #PAGE
  root 'pages#index'

  #ADMIN
  namespace :admin, path: 'admin' do
    resources :users
    get 'sign_up', to: 'users#new'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  
  validates :username, presence: true, uniqueness: { case_sensitive: false}, length: {minimum: 3, maximum: 20}
  validates :email, presence: true, uniqueness: { case_sensitive: false}, length: {maximum: 100}
  
  has_secure_password
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
    #  the order of before_action matters here
    before_action :login_check, except: [:new]
    before_action :find_user, only:[:edit,:show, :update, :destroy]
    before_action :same_user_check, only: [:edit,:update, :destroy]
    before_action :admin_check

    def index
      @users = User.all
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to root_path, notice: "#{@user.username} 已註冊成功！"
      else
        @error_message = @user.errors.full_messages.to_sentence
        render :new
      end
    end
  
    def edit
    end
  
    def show
    end
  
    def update
      if @user.update(user_params)
        redirect_to admin_users_path, notice: "更新帳戶成功"
      else
        @error_message = @user.errors.full_messages.to_sentence
        render :edit
      end
    end
  
    def destroy
      admin_count = User.where(admin: true).count
      
      if admin_count <= 1 && @user.admin
        redirect_to admin_users_path, notice: "無法刪除唯一管理者"        
      else
        if @user.destroy
          redirect_to admin_users_path, notice: "刪除帳戶成功"
        end
      end
      # debugger
    end
  
    private
    def find_user
      @user = User.find_by(id: params[:id])
    end
  
    def user_params
      params.require(:user).permit(:username, :email, :password, :admin)
    end

    # def same_user_check
    #   if current_user != @user
    #     redirect_to users_path, notice: "你只能編輯或刪除自己的帳戶資訊"
    #   end
    # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_check, except: [:new, :create]
  before_action :find_user, only:[:edit,:show, :update, :destroy]
  before_action :same_user_check, only: [:edit,:update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "#{@user.username} 已註冊成功！"
    else
      @error_message = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @user.update(user_params)
      redirect_to user_tasks_path(current_user), notice: "更新帳戶成功"
    else
      @error_message = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to user_tasks_path(current_user), notice: "刪除帳戶成功"
    end
  end

  private
  def find_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form_user.html.erb
<h3> <%= error_message %> </h3>

<%= simple_form_for [:admin, user] do |form| %>
  <div class="wrap">
    <%= form.input :username, label: t("attributes.users.username") %> 
    <%= form.input :email, label: t("attributes.users.email") %>
    <%= form.input :password, label: t("attributes.users.password") %>
    <%= form.input :admin, label: t("attributes.users.register_admin")  %>

    <%= form.submit%>
  </div>

<% end %>

app/views/admin/users/edit.html.erb
<h1>編輯使用者</h1>

<%= render 'form_user', user: @user, error_message: @error_message %>

app/views/admin/users/index.html.erb
<h1><%= t('attributes.tasks.backend') %>： <%=t('users.index_user') %></h1>

<%#= paginate @users, theme: 'twitter-bootstrap-4' %>

<table class="table table-hover">
  <thead>
    <tr>
      <td><%= t('attributes.users.username') %></td>
      <td><%= t('attributes.users.email') %></td>
      <td><%= t('attributes.tasks.task_count') %></td>
      <td><%= t('attributes.users.role') %></td>
      <td><%= t('attributes.users.action') %></td>
    </tr>
  </thead>
  
  <tbody>
    <% @users.each do |user| %>
      <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.tasks.count %></td>
      <td><%= user_role(user.admin) %></td>
      <td>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%#= current_user.username.upcase %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to t("users.edit"), edit_admin_user_path(user) , class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>          
          <%= link_to t("users.show"), admin_user_path(user) , class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to t("users.delete"), admin_user_path(user) , class: 'dropdown-item', method: 'delete', data: { confirm: "確認刪除嗎？"}%>
        </div>
      </td>
    </tr>
    <% end %>

  </tbody>
</table>

<%= button_to t("users.create"), admin_sign_up_path ,class:"btn btn-outline-dark", method: "get"%>

app/views/admin/users/new.html.erb
<h1>新增使用者</h1>

<%= render 'form_user', user: @user, error_message: @error_message %>

app/views/admin/users/show.html.erb
  <div class="card" style="width: 50rem;">
    <h1><div class="card-header"> <%= t("attributes.users.account_info") %></div></h1>

    <ul class="list-group list-group-flush">
      <li class="list-group-item"> <%= t("attributes.users.role") %>: <%= user_role(@user.admin)  %></li>
      <li class="list-group-item"> <%= t("attributes.users.email") %>: <%= @user.email %> </li>
      <li class="list-group-item"> <%= t("attributes.users.username") %>: <%= @user.username %> </li>
    </ul>
  </div>